# https://taskfile.dev

version: "3"

vars:
  GREETING: --------------

tasks:
  default:
    cmds:
      - task -l
      - echo "{{.GREETING}}"
    silent: true

  dispatch-to-dir:
    desc: _
    cmds:
      - task -d {{.target_dir}} {{.task}}

  spin-up-flow: &with_simple_jenkins
    vars:
      task:  '{{splitList ":" .TASK | last}}'
      target_dir: decks/simple-jenkins-master
    desc: spinup {{.target_dir}}
    cmds:
    - task: dispatch-to-dir
      vars:
        target_dir: '{{.target_dir}}'
        task: '{{.task}}'

  show-urls:
    <<: *with_simple_jenkins
    desc: show urls
