# https://taskfile.dev

version: '3'

vars:
  GREETING: --------------

tasks:
  default:
    cmds:
      - task -l
      - echo "{{.GREETING}}"
    silent: true
  
  get-started:
    desc: bootstrap instructions
    cmds:
      - |-
        echo '
        
        '