# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  deploy-project:
    desc: _
    cmds:
      - kubectl apply -f project.yaml -n argocd
