version: "3.9"
services:
  jencondait.samexample.com:
    hostname: 'jencondait.samexample.com'
    image: "${DCVAR_JENCONDA_DIMG_ADDR}"
    ports:
      - "${DCVAR_UI_JENKINS_PORT_EXT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      net_cicd_net:

# --- networks:net_cicd_net ---
networks:
  net_cicd_net:
    external: true