# https://taskfile.dev

version: "3"

env: &merge_env
  DCVAR_JENCONDA_DIMG_ADDR: yairdar/jenconda:0.8.3-1633076394
  DCVAR_UI_JENKINS_PORT_EXT: "28082"

vars:
  <<: *merge_env
  docker_compose_yaml: docker-compose.yaml

tasks:
  spin-up-flow:
    desc: restart componets
    cmds:
      - task: spin-down
        vars:
          safe_run: "true"
      - task: spin-up-flow.prepare
      - task: spin-up
      - task: show-urls

  show-env-ac:
    desc: show environment activate cmd
    silent: true
    cmds:
      - |-
        echo '
        export DCVAR_JENCONDA_DIMG_ADDR={{.DCVAR_JENCONDA_DIMG_ADDR}}
        export DCVAR_UI_JENKINS_PORT_EXT={{.DCVAR_UI_JENKINS_PORT_EXT}}
        '

  show-urls:
    desc: shows urls of services
    silent: true
    cmds: ['echo "{{._show_url_exp}}" ']
    vars:
      _show_url_exp: |-
        ui-jenkins-url: http://localhost:${DCVAR_UI_JENKINS_PORT_EXT}

  spin-up-flow.prepare:
    desc: _
    cmds:
      - echo "{{.TASK}} done deps"

  spin-up:
    desc: _
    cmds:
      - docker-compose -f {{.docker_compose_yaml}} up  -d

  spin-down:
    desc: _
    vars:
      rest_suff: "{{if .safe_run}}| true{{else}} {{end}}"
    cmds:
      - docker-compose -f {{.docker_compose_yaml}} down {{.rest_suff}}
