# https://taskfile.dev
# https://github.com/eea/eea.docker.jenkins.slave-dind
version: "3"

env: &merge_env
  DCVAR_JENCONDA_DIMG_ADDR: yairdar/jenconda:0.8.7-1634602016
  DCVAR_UI_JENKINS_PORT_EXT: "28082"

vars:
  <<: *merge_env
  docker_compose_yaml: docker-compose.yaml

tasks:
  append-dnd-server:
    desc: _
    cmds:
      - |-
        docker run -d --name=docker17 --hostname docker17 \
        --network net_cicd_net \
        -p "2375" \
        --privileged=true \
        docker:1.13-dind
  # append-dnd-server:
  #   desc: _
  #   cmds:
  #     - |-
  #       docker-compose up -d dnd.server.com

  append-dnd-worker:
    desc:
    cmds:
      - |-
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --privileged=true \
        --network net_cicd_net \
        --link docker17 \
        -e DOCKER_HOST=tcp://docker17:2375 \
        -e JAVA_OPTS="-Xmx2048m" \
        -e JENKINS_MASTER="http://jencondait.samexample.com:8080" \
        -e JENKINS_NAME="dnd-worker" \
        -e JENKINS_USER=tester \
        -e JENKINS_PASS=tester123 \
        -e JENKINS_RETRY="10" \
        yairdar/jen_dnd_worker:0.8.7-1634602016
      # eeacms/jenkins-slave-dind:19.03-3.26-2

  append-worker:
    desc:
    cmds:
      - |-
        docker run -d \
        --network net_cicd_net \
        -e JAVA_OPTS="-Xmx2048m" \
        -e JENKINS_MASTER="http://jencondait.samexample.com:8080" \
        -e JENKINS_NAME="worker" \
        -e JENKINS_USER=tester \
        -e JENKINS_PASS=tester123 \
        -e JENKINS_RETRY="10" \
        eeacms/jenkins-slave

  spin-up-flow:
    desc: restart componets
    cmds:
      - task: spin-down
        vars:
          safe_run: "true"
      - task: spin-up-flow.prepare
      - task: spin-up
      - task: show-urls

  show-env-ac:
    desc: show environment activate cmd
    silent: true
    cmds:
      - |-
        echo '
        export DCVAR_JENCONDA_DIMG_ADDR={{.DCVAR_JENCONDA_DIMG_ADDR}}
        export DCVAR_UI_JENKINS_PORT_EXT={{.DCVAR_UI_JENKINS_PORT_EXT}}
        '

  show-urls:
    desc: shows urls of services
    silent: true
    cmds: ['echo "{{._show_url_exp}}" ']
    vars:
      _show_url_exp: |-
        ui-jenkins-url: http://localhost:${DCVAR_UI_JENKINS_PORT_EXT}

  spin-up-flow.prepare:
    desc: _
    cmds:
      - echo "{{.TASK}} done deps"

  ensure-network:
    desc: _
    status:
    - docker network inspect net_cicd_net
    cmds:
    - docker network create -d bridge net_cicd_net

  spin-up:
    desc: _
    deps:
      - task: ensure-network
    cmds:
      - docker-compose -f {{.docker_compose_yaml}} up  -d

  spin-down:
    desc: _
    vars:
      rest_suff: "{{if .safe_run}}| true{{else}} {{end}}"
    cmds:
      - docker-compose -f {{.docker_compose_yaml}} down {{.rest_suff}} || true

  remove:
    desc: _
    cmds:
      - docker-compose -f {{.docker_compose_yaml}} down {{.rest_suff}} || true

  recreate:
    desc: _
    cmds:
      - task: remove
      - task: spin-up-flow
